server:
  port: 18002
  use-forward-headers: true
  servlet:
    session:
      timeout: 86400s
      cookie:
        http-only: true
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 28002
  application:
    serialize-check-status: WARN
    qos-enable: true
    name: SdsArticleApplication
    qos-port: 38002
    qos-accept-foreign-ip: false
    logger: slf4j
